import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Wrapper from "@/components/UI/wrapper/Wrapper";
import TopContent from "@/components/MainPage/TopContent/TopContent";
import PopularTour from "@/components/MainPage/popularTour/PopularTour";
import SeasonalTour from "@/components/MainPage/seasonalTour/SeasonalTour";
import OneDayTour from "@/components/MainPage/oneDayTour/OneDayTour";
import CreationTour from "@/components/MainPage/creationTour/CreationTour";
import Info from "@/components/MainPage/info/Info";
import Reasons from "@/components/MainPage/reasons/Reasons";
import Directions from "@/components/MainPage/directions/Directions";
import Blog from "@/components/MainPage/blog/Blog";
import News from "@/components/MainPage/news/News";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Туры в Узбекистан на 2023 год с ценами, отзывами из Москвы и Спб.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <TopContent />
        <PopularTour  title={"Популярные туры в Узбекистан"} />
        <SeasonalTour title={"Сезонные авторские туры"} />
        <OneDayTour title={"Туры на один день"}/>
        <CreationTour/>
        <Reasons/>
        <Directions/>
        <Blog/>
        <News/>
        <Info/>
      </Wrapper>
    </>
  );
}
